# Generated by Django 5.2.14 on 2026-06-05 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0021_widen_workflow_integer_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("key", models.CharField(max_length=16, verbose_name="key")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_department_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="lead",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="department_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="members",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ("workspace__name", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProjectCycle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("starts_at", models.DateField(verbose_name="starts at")),
                ("ends_at", models.DateField(verbose_name="ends at")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project cycle",
                "verbose_name_plural": "project cycles",
                "ordering": ("-starts_at", "name"),
            },
        ),
        migrations.CreateModel(
            name="ProjectIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=16,
                        verbose_name="priority",
                    ),
                ),
                (
                    "estimate",
                    models.PositiveIntegerField(default=0, verbose_name="estimate"),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="due date"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="completed at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_project_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assignee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_issues",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issues",
                        to="documents.projectcycle",
                        verbose_name="cycle",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project issue",
                "verbose_name_plural": "project issues",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IntakeRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "source_department",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="source department",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="open",
                        max_length=16,
                        verbose_name="status",
                    ),
                ),
                (
                    "review_comment",
                    models.TextField(blank=True, verbose_name="review comment"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_intake_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="requester",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_requests",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
                (
                    "accepted_issue",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_request",
                        to="documents.projectissue",
                        verbose_name="accepted issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "intake request",
                "verbose_name_plural": "intake requests",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ProjectLabel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "color",
                    models.CharField(
                        default="#6b7280",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project label",
                "verbose_name_plural": "project labels",
                "ordering": ("project", "name"),
            },
        ),
        migrations.AddField(
            model_name="projectissue",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                related_name="issues",
                to="documents.projectlabel",
                verbose_name="labels",
            ),
        ),
        migrations.CreateModel(
            name="ProjectModule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "target_date",
                    models.DateField(blank=True, null=True, verbose_name="target date"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project module",
                "verbose_name_plural": "project modules",
                "ordering": ("project", "name"),
            },
        ),
        migrations.AddField(
            model_name="projectissue",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="documents.projectmodule",
                verbose_name="module",
            ),
        ),
        migrations.CreateModel(
            name="ProjectPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "content",
                    models.JSONField(blank=True, default=list, verbose_name="content"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_project_pages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project page",
                "verbose_name_plural": "project pages",
                "ordering": ("project", "title"),
            },
        ),
        migrations.CreateModel(
            name="ProjectState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="position"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="is default"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="is completed"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="documents.project",
                        verbose_name="project",
                    ),
                ),
            ],
            options={
                "verbose_name": "project state",
                "verbose_name_plural": "project states",
                "ordering": ("project", "position", "name"),
            },
        ),
        migrations.AddField(
            model_name="projectissue",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="documents.projectstate",
                verbose_name="state",
            ),
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="settings"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="department_workspaces",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="members",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "workspace",
                "verbose_name_plural": "workspaces",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="documents.workspace",
                verbose_name="workspace",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcycle",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="documents_projectcycle_unique_name_project",
            ),
        ),
        migrations.AddIndex(
            model_name="intakerequest",
            index=models.Index(
                fields=["project", "status"],
                name="documents_i_project_ef6e2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="intakerequest",
            index=models.Index(
                fields=["requester", "created_at"],
                name="documents_i_request_754812_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectlabel",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="documents_projectlabel_unique_name_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmodule",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="documents_projectmodule_unique_name_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectpage",
            constraint=models.UniqueConstraint(
                fields=("project", "title"),
                name="documents_projectpage_unique_title_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectstate",
            constraint=models.UniqueConstraint(
                fields=("project", "name"),
                name="documents_projectstate_unique_name_project",
            ),
        ),
        migrations.AddIndex(
            model_name="projectissue",
            index=models.Index(
                fields=["project", "state"],
                name="documents_p_project_22bb9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectissue",
            index=models.Index(
                fields=["assignee", "created_at"],
                name="documents_p_assigne_1f26c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectissue",
            index=models.Index(
                fields=["cycle", "created_at"],
                name="documents_p_cycle_i_4e81bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectissue",
            index=models.Index(
                fields=["module", "created_at"],
                name="documents_p_module__b9f9a6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                fields=("name", "owner"),
                name="documents_workspace_unique_name_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["workspace", "key"],
                name="documents_p_workspa_9fa3b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["owner", "created_at"],
                name="documents_p_owner_i_699d68_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("workspace", "key"),
                name="documents_project_unique_key_workspace",
            ),
        ),
    ]
